"""Emit findings into ECP's existing remediation pipeline formats (CSV + Markdown + JSON)."""
from __future__ import annotations

import csv
import json
import re
from collections import defaultdict
from dataclasses import asdict
from datetime import date
from pathlib import Path

from .ai_analyzer import Finding


def collapse_errors(errors: list[str]) -> list[str]:
    """Collapse repeated denials across targets into one summarized line each.

    'nmap-smb 1.2.3.4: DENIED [scope] ...'  x3  ->  'DENIED [scope] ... (3 targets: ...)'.
    """
    groups: dict[str, list[str]] = defaultdict(list)
    for e in errors:
        m = re.match(r"\s*\S+\s+(\S+):\s*(.*)", e)
        if m:
            groups[m.group(2)].append(m.group(1))
        else:
            groups[e].append("")
    out = []
    for reason, targets in groups.items():
        ts = [t for t in targets if t]
        out.append(f"{reason} ({len(ts)} targets: {', '.join(ts)})" if len(ts) > 1 else
                   (f"{ts[0]}: {reason}" if ts else reason))
    return out

# Columns aligned to ECP_Remediation_Tickets.csv so findings drop straight into the tracker.
CSV_COLUMNS = ["ticket_id", "title", "severity", "cvss31", "mitre", "asset", "platform",
               "evidence", "remediation", "mitigation_steps", "confidence", "status", "opened"]


def write_all(result, out_dir: Path | str) -> dict[str, Path]:
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    today = date.today().isoformat()
    paths = {
        "json": out / "findings.json",
        "csv": out / "ECP_Aegis_Findings.csv",
        "md": out / "ECP_Aegis_Report.md",
    }

    paths["json"].write_text(json.dumps({
        "findings": [asdict(f) for f in result.findings],
        "correlation": result.correlation,
        "errors": result.errors,
    }, indent=2))

    with paths["csv"].open("w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=CSV_COLUMNS)
        w.writeheader()
        for i, f in enumerate(result.findings, 1):
            w.writerow({
                "ticket_id": f"AEGIS-{today}-{i:03d}", "title": f.title,
                "severity": f.severity, "cvss31": f.cvss31_vector, "mitre": f.mitre_attack,
                "asset": f.affected_asset, "platform": f.platform,
                "evidence": f.evidence[:200], "remediation": f.remediation,
                "mitigation_steps": " | ".join(f.mitigation_steps),
                "confidence": f.confidence, "status": "Open", "opened": today,
            })

    paths["md"].write_text(_markdown(result, today))
    return paths


def _markdown(result, today: str) -> str:
    c = result.correlation
    lines = [f"# ECP Aegis — Pentest Findings ({today})", "",
             "> Authorized internal sandbox assessment. Generated by ECP Aegis.", "",
             "## Executive summary", "", c.get("executive_summary", "—"), ""]
    if c.get("attack_paths"):
        lines += ["## Attack paths", ""]
        for p in c["attack_paths"]:
            lines.append(f"### {p.get('name', '?')} — {p.get('severity', '?')}")
            for s in p.get("steps", []):
                lines.append(f"- {s}")
            lines.append(f"- **Business risk:** {p.get('business_risk', '')}")
            lines.append("")
    if c.get("phi_exposure"):
        lines += ["## PHI / HIPAA exposure", "",
                  *[f"- {a}" for a in c["phi_exposure"]], ""]
    lines += ["## Findings", "",
              "| Sev | Title | Asset | CVSS | MITRE | Conf |",
              "|-----|-------|-------|------|-------|------|"]
    rank = {"Critical": 4, "High": 3, "Medium": 2, "Low": 1, "Info": 0}
    ordered = sorted(result.findings, key=lambda x: rank.get(x.severity, 0), reverse=True)
    for f in ordered:
        lines.append(f"| {f.severity} | {f.title} | {f.affected_asset} | "
                     f"{f.cvss31_vector} | {f.mitre_attack} | {f.confidence} |")
    # Step-by-step, platform-specific remediation playbook per finding.
    lines += ["", "## Remediation playbook (step-by-step)", ""]
    for f in ordered:
        lines.append(f"### [{f.severity}] {f.title}")
        meta = " · ".join(filter(None, [f.affected_asset, f.platform, f.mitre_attack]))
        if meta:
            lines.append(f"*{meta}*")
        lines.append("")
        for step in (f.mitigation_steps or [f.remediation or "Review and remediate."]):
            lines.append(step if step[:1].isdigit() else f"- {step}")
        lines.append("")
    if result.errors:
        lines += ["", "## Denied / errors (guardrail)", "",
                  *[f"- {e}" for e in collapse_errors(result.errors)]]
    return "\n".join(lines) + "\n"
